
name: Package and Upload

on: ['push']

jobs:
  package_and_upload:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tinyjs
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build python package
        run: pip install --upgrade build && python -m build

      - name: Upload package to pypi
        uses: pypa/gh-action-publish@release/v1